universe = vanilla

############# Script variables #############
NETABBR = n10r0
OUTPUTFILEPATH = /mnt/ws/home/nkolbow/repos/snaq2/data/output/n10r0.csv
NUMGT = 100
ILS = low

# REPLICATENUM is actually changed later in the `queue` command
REPLICATENUM = 2

# NUMPROCS should actually be `<numprobs> - 1` b/c of julia reasons
NUMPROCS = 1
############################################


log = condor_logs/run_one_$(Cluster).log
error = condor_logs/run_one_$(Cluster)_$(Process).err
output = condor_logs/run_one_$(Cluster)_$(Process).out

############################################################################################
executable = scripts/julia_setup.sh
arguments = $(NETABBR) $(OUTPUTFILEPATH) $(NUMGT) $(NUMPROCS) $(ILS) $(REPLICATENUM)
############################################################################################
# Arguments:
# 1. network abbreviation (i.e. data/input/<ARG1>/)
# 2. output CSV filepath
# 3. number of gene trees
# 4. number of processors MINUS ONE (i.e. 1 ==> 2 procs are used)
#   - this is because `julia -pN` runs julia with N __additional__ processors, not N procs
# 5. level of ILS
# 6. replicate ID
############################################################################################

should_transfer_files = YES
transfer_input_files = transfer-files/julia_setup.sh, transfer-files/julia-package-install.jl, transfer-files/julia-1.9.3-linux-x86_64.tar.gz, ../pipelines/helper-fxns.jl, ../pipelines/network-to-est-gts.jl, ../pipelines/run-one.sh, ../pipelines/snaq1.0-estimation.jl, ../pipelines/snaq2.0-estimation.jl, ../software/iqtree-1.6.12-linux, ../software/seq-gen-linux, ../pipelines/write-results.jl

request_cpus = 2
request_memory = 4GB
request_disk = 1GB

queue